"""table Person, new columns: email, city, address

Revision ID: 74f68ac63086
Revises: 4a2b59c37fe2
Create Date: 2024-04-01 10:13:15.794529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f68ac63086'
down_revision = '4a2b59c37fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
